FROM ramesesinc/enterprise-server:v001

COPY /mainds /apps/server/services/datasources/mainds
COPY /adapters /apps/server/services/apps/enterprise/adapters/ext
COPY /connections /apps/server/services/apps/enterprise/connections/ext
COPY /modules /apps/server/services/apps/enterprise/modules
