version: "3"

services:
  
  docs-server:
    image: ramesesinc/cloud-docs-server:1.0.0
    container_name: docs-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    ports:
      - "4000:4000"
    volumes:
      - /home/rameses/RAMESES-DEV/mobile:/apps/server/docs:ro 
      
