FROM ramesesinc/enterprise-server:v001

COPY /modules /apps/server/services/apps/enterprise/modules
COPY /connections /apps/server/services/apps/enterprise/connections
COPY /mainds /apps/server/services/datasources/mainds
