FROM ramesesinc/enterprise-server:255.03

COPY /modules /services/modules
COPY /datasources /services/datasources
COPY /adapters /apps/enterprise/adapters
COPY /connections /apps/enterprise/connections
COPY /modules.conf /apps/enterprise/modules.conf
