version: "3"
services:
  migration-server:
    image: ramesesinc/calendar-server:0.0.1
    container_name: calendar-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - "5002:5000"
    environment:
      TZ: "Asia/Manila"
    volumes:
      - ./credentials:/apps/server/credentials
    