FROM ramesesinc/enterprise-server:255.01

COPY /datasources /apps/server/services/datasources
COPY /adapters /apps/server/services/apps/enterprise/adapters
COPY /connections /apps/server/services/apps/enterprise/connections
COPY /modules.conf /apps/server/services/apps/enterprise/modules.conf
COPY /modules /apps/server/services/modules
